---
title: "Databricks REPL"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Job Management}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
library(brickster)
```

# Running Code Remotely

`{brickster}` provides mechanisms to run code against Databricks, below is an overview of the available of those in the package:

+---------------------------------------------------------------------------------------------------------------------------------+-----------------------+-------------------------------------------------------------------------------+
| Method                                                                                                                          | Compatible Compute    | Notes                                                                         |
+=================================================================================================================================+=======================+===============================================================================+
| [SQL execution API](https://docs.databricks.com/api/workspace/statementexecution)\                                              | SQL Warehouse         | Lower level functions that align 1:1 with API endpoints                       |
| ([`db_sql_exec_*`](https://databrickslabs.github.io/brickster/reference/index.html#sql-statement-execution))                    |                       |                                                                               |
+---------------------------------------------------------------------------------------------------------------------------------+-----------------------+-------------------------------------------------------------------------------+
| [Command execution API](https://docs.databricks.com/api/workspace/commandexecution)\                                            | Clusters\             | Lower level functions that align 1:1 with API endpoints                       |
| ([`db_context_*`](https://databrickslabs.github.io/brickster/reference/index.html#execution-contexts))                          | (Shared, Single User) |                                                                               |
+---------------------------------------------------------------------------------------------------------------------------------+-----------------------+-------------------------------------------------------------------------------+
| [`{brickster}` custom `{knitr}` engine](https://databrickslabs.github.io/brickster/articles/rmarkdown-databricks-notebook.html) | Clusters\             | **Not intended for report generation.**                                       |
|                                                                                                                                 | (Shared, Single User) |                                                                               |
|                                                                                                                                 |                       | Provides mechanism to interactively run code via RMarkdown.                   |
+---------------------------------------------------------------------------------------------------------------------------------+-----------------------+-------------------------------------------------------------------------------+
| [Databricks SQL Connector](https://docs.databricks.com/en/dev-tools/python-sql-connector.html) via `{reticulate}`\              | SQL Warehouse         | Exposes `databricks.sql` connector to R.                                      |
| ([`db_sql_client`](https://databrickslabs.github.io/brickster/reference/index.html#sql-connector))                              |                       |                                                                               |
+---------------------------------------------------------------------------------------------------------------------------------+-----------------------+-------------------------------------------------------------------------------+
| Databricks REPL\                                                                                                                | Clusters\             | Supports all notebook languages, R is only supported on single user clusters. |
| (`db_repl`)                                                                                                                     | (Shared, Single User) |                                                                               |
+---------------------------------------------------------------------------------------------------------------------------------+-----------------------+-------------------------------------------------------------------------------+

Databricks [REPL](https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop'=) (`db_repl()`) will be the focus of this article.

# What is the Databricks REPL?

The REPL temporarily connects the existing R console to a Databricks cluster (via [command execution APIs](https://docs.databricks.com/api/workspace/commandexecution)) and allows code in all supported languages to be sent interactively - as if it were running locally.

## Limitations

-   Development environments (e.g. RStudio, Positron) won't display variables from the remote contexts in the environment pane

-   HTML content will only render for Python, `{htmlwidgets}` rendering is restricted due to [notebook limitations that require a workaround](https://docs.databricks.com/en/visualizations/htmlwidgets.html) currently

-   
